### ISSUE TITLE
Sedna Zigbee Valve Switch Disappeared After 2024.8.0 Update

### ISSUE THREAD

**Issue by mtwo** [claudegel/sinope-zha#48]
The switch control on my Sedna VA4220ZB disappeared after updating Home Assistant to 2024.8.0. I've attempted to re-pair it both with and without the custom quirk, and in both cases I no longer have a way of opening or closing it. I _think_ that I read something in a previous release about valves no longer needing to be represented as switches, could this be related?

**Comment by saucepwn** [comment]
This is with the ZHA integration

**Comment by claudegel** [comment]
Hi, I just made the update to 2024-8.0. I'll check.

Yes the valve entity is now separated from the switch but ZHA didn't make the change until now. It is possible that in 2024.8.0 they finally added the valve. If yes I'll  push a PR to my sinope-zha and when stable to ZHA quirks.
Let me check if the valve entity are now in ZHA.
You can add logging in HA for ZHA. Add this to configuration.yaml and restart HA
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    homeassistant.components.zha: debug
    zhaquirks: debug
    zigpy.zcl: debug
    zigpy.application: debug
```
You should get something in the home-assistant.log
