### ISSUE TITLE
Just Purchased the Sinope Technologies LM4110-ZB

### ISSUE THREAD

**Issue by Dhostetter** [claudegel/sinope-zha#63]
I just purchased the Sinope Technologies LM4110-ZB sensor.
Added it to HA via ZHA without an issue.
But I don't not see a sensor for the tank reading.
I get the following sensor info:
Temperature
Battery
Identity
Not Shown:
LQI
RSSI

Did the tank level show up after adding or did you need to do something else?
Not sure what to do at this point.

Any assistance would be appreciated.

**Comment by claudegel** [comment]
Hi once the LM4110ZB is installed in ZHA you need to perform many opertions in order to get the level percent. This device do not report the level % of the tank but the angle of the tank gauge needle. So you need to perform those steps:
1- setup reporting on the device
2- bind the device to your gateway so it can send the report to
3- make an automation that will get the reported angle 
4- make an input_number to set the gauge offset in configuration.yaml
5- make an input_text variable to put the gauge type you have on the tank, 10-80 or 5-95
6- make a sensor that will do the calculations and show the % level value.

Very simple. Just follow the instructions on my readme.md on this sinope-zha component
nce done you'll be able to set alarm for minimum tank level as you like

**Comment by Dhostetter** [comment]
Claude,Thanks so much for responding.I'm slowly getting it together.I'm getting an error in the template.- trigger: - platform: time_pattern <- String does not match the pattern of "Legacy_Syntex^". hours: "/5"Any suggestions on how to correct this error?Get BlueMail for DesktopClaude Gelinas wrote:
Hi once the LM4110ZB is installed in ZHA you need to perform many opertions in order to get the level percent. This device do not report the level % of the tank but the angle of the tank gauge needle. So you need to perform those steps:
1- setup reporting on the device
2- bind the device to your gateway so it can send the report to
3- make an automation that will get the reported angle
4- make an input_number to set the gauge offset in configuration.yaml
5- make an input_text variable to put the gauge type you have on the tank, 10-80 or 5-95
6- make a sensor that will do the calculations and show the % level value.
Very simple. Just follow the instructions on my readme.md on this sinope-zha component
nce done you'll be able to set alarm for minimum tank level as you like —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by claudegel** [comment]
We need to change the trigger part like this
```
template:
  - trigger:
    - trigger: time_pattern
      hours: "/5"
```
platform should be replaced by trigger

**Comment by Dhostetter** [comment]
Claudegel,
I haven't been able to get the tank level to show up. I've tried a couple of things to try and troubleshoot but nothing seems to work.
Here's where I'm at.
I'm using the second automation to retrieve the data. 
When I execute the command thru developer tools, I get this info:
zha_toolkit_version: v1.1.25
zigpy_version: 0.74.0
zigpy_rf_version: 0.13.1
ieee_org:
  - 63
  - 229
  - 171
  - 254
  - 255
  - 101
  - 17
  - 44
ieee: 2c:11:65:ff:fe:ab:e5:3f
command: attr_read
command_data: null
start_time: "2025-02-03T14:55:09.659185+00:00"
errors: []
params:
  cluster_id: 12
  attr_id: 85
  dir: 0
  tries: 100
  expect_reply: true
  args: []
  kwargs: {}
  state_id: sensor.current_angle
  allow_create: true
  read_before_write: true
  read_after_write: true
attr_type: "0x39"
write_is_equal: false
result_read:
  - "85": 351
  - {}
success: true

I've added the input gauge_offset, tank_gauge, & tank remaining level template to my config yml file.
All entities show in HA helpers. The guage_offset doesn't show under HA entities. 
When I look at the template entity its status is either not provided or unavailable.

Any suggestions on how to troubleshoot this?

**Comment by claudegel** [comment]
I've noticed that there was an indentation error in the second automation for the trigger.
```
- id: '1692841759194'
  alias: Lecture niveau propane
  description: Lecture du niveau de réservoir à chaque heure
  triggers:
    - trigger: time_pattern
      hours: /1
  condition: []
  actions:
    action:
      - service: zha_toolkit.execute
        data:
          command: attr_read
          ieee: "«your LM4110 ieee »"
          cluster: 12
          attribute: 85
          state_id: sensor.current_angle
          allow_create: true
          tries: 100
  mode: single
```
did you create your input_number and input_text in configuration.yaml ?
